# template_engine.py

import json
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime


class ProductionTemplateEngine:
    """
    FINAL – SME-friendly contract template engine (India-focused)
    """

    def __init__(self, template_dir: str = "templates"):
        self.template_dir = Path(template_dir)
        self.template_dir.mkdir(parents=True, exist_ok=True)

        self.templates = {}
        self._ensure_default_templates()
        self._load_templates()

    # ------------------------------------------------------------------
    # PUBLIC API
    # ------------------------------------------------------------------

    def list_templates(self) -> Dict[str, Dict]:
        return self.templates

    def get_template(self, contract_type: str) -> Optional[Dict]:
        return self.templates.get(contract_type)

    def get_required_variables(self, contract_type: str) -> Dict[str, Any]:
        tpl = self.get_template(contract_type)
        return tpl.get("variables", {}) if tpl else {}

    def generate_contract(
        self,
        contract_type: str,
        values: Dict[str, Any]
    ) -> Dict[str, Any]:

        template = self.get_template(contract_type)
        if not template:
            return {"success": False, "error": "Template not found"}

        missing = [
            k for k, v in template["variables"].items()
            if v.get("required") and k not in values
        ]

        if missing:
            return {
                "success": False,
                "error": f"Missing required variables: {', '.join(missing)}"
            }

        text = template["template"]

        for key, value in values.items():
            text = text.replace(f"{{{key}}}", str(value))

        text += self._footer(values)

        return {
            "success": True,
            "contract_type": contract_type,
            "template_name": template["name"],
            "generated_text": text,
            "generated_at": datetime.utcnow().isoformat()
        }

    # ------------------------------------------------------------------
    # TEMPLATE MANAGEMENT
    # ------------------------------------------------------------------

    def _load_templates(self):
        for file in self.template_dir.glob("*.json"):
            data = json.loads(file.read_text(encoding="utf-8"))
            self.templates[data["type"]] = data

    def _ensure_default_templates(self):
        path = self.template_dir / "employment_agreement.json"
        if path.exists():
            return

        employment_template = {
            "type": "employment_agreement",
            "name": "Indian SME Employment Agreement",
            "version": "1.0",
            "variables": {
                "COMPANY_NAME": {"required": True},
                "EMPLOYEE_NAME": {"required": True},
                "POSITION": {"required": True},
                "START_DATE": {"required": True},
                "MONTHLY_SALARY": {"required": True},
                "NOTICE_PERIOD_DAYS": {"required": True},
                "JURISDICTION_CITY": {"required": True}
            },
            "template": """
EMPLOYMENT AGREEMENT

This Employment Agreement is entered into between:

{COMPANY_NAME} ("Employer")
and
{EMPLOYEE_NAME} ("Employee")

1. POSITION
The Employee shall serve as {POSITION} starting from {START_DATE}.

2. COMPENSATION
The Employee shall receive a monthly salary of INR {MONTHLY_SALARY}, subject to applicable taxes.

3. CONFIDENTIALITY
Employee shall maintain confidentiality of proprietary information during and after employment.

4. INTELLECTUAL PROPERTY
Any work created during employment shall belong to Employer. Pre-existing IP remains with Employee.

5. TERMINATION
Either party may terminate this agreement with {NOTICE_PERIOD_DAYS} days written notice.

6. GOVERNING LAW
This Agreement shall be governed by the laws of India.
Courts at {JURISDICTION_CITY} shall have jurisdiction.

Signed by both parties in good faith.
"""
        }

        path.write_text(json.dumps(employment_template, indent=2))

    # ------------------------------------------------------------------
    # UTILITIES
    # ------------------------------------------------------------------

    def _footer(self, values: Dict[str, Any]) -> str:
        return f"""

---
Generated by SME Legal Assistant
Date: {datetime.utcnow().strftime('%d %B %Y')}

DISCLAIMER:
This document is a template for informational purposes only.
It does not constitute legal advice.
Consult a qualified legal professional before execution.

CONFIDENTIAL:
For internal use of {values.get('COMPANY_NAME', 'Client')} only.
"""
